RedditClone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users
  resource :session, only: [:destroy, :new, :create]
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

    validates :username, :session_token, uniqueness: true, presence: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 7}, allow_nil: true

    before_validation :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(username, password)
        user = self.find_by(username: username)
        return nil unless user
        user.is_password?(password) ? user : nil
    end
       
    def is_password?(pass)
        pass_obj = BCrypt::Password.new(self.password_digest)
        pass_obj.is_password?(pass)
    end

    def password=(pass)
        self.password_digest = BCrypt::Password.create(pass)
        @password = pass
    end

    def reset_session_token!
        self.session_token = generate_token
        self.save!
        self.session_token
    end

    private

    def generate_token
        SecureRandom::urlsafe_base64
    end

    def ensure_session_token
        self.session_token ||= generate_token
    end

end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def require_logged_in?
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to user_url(current_user) if logged_in?
    end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    # skip_forgery_protection

    #skip_before_action :verify_authenticity_token

    before_action :require_logged_in?, only: [:destroy]
    before_action :require_logged_out, only: [:new, :create]

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            @user = User.new(username: params[:user][:username], password:params[:user][:password] )
            flash[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def destroy
        logout! if logged_in?
        redirect_to new_session_url
    end

    def new
        @user = User.new
    end

end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in?, only: [:show, :destroy, :index, :update, :edit]
    before_action :require_logged_out, only: [:new, :create]

    def new
        @user = User.new
        # redirect_to new_user_url
        render :new
    end

    def destroy
        @user = current_user
        logout!
        @user.destroy
        render :new
        
        # render :new is faster than redirecting since it doesn't make another HTTP request
        # redirect_to new_user_url
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def index
        @users = User.all
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    def update
        @user = current_user
        @user.username = user_params[:username]
        @user.save!
        redirect_to user_url(@user)
    end

    def edit
        @user = current_user
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

    def require_logged_in?
        redirect_to new_user_url unless logged_in?
    end
end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>

    <% if logged_in? %>
      <form action="<%= user_url(current_user.id) %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">

        <input type="submit" value="Delete User">
      </form>

      <form action="<%= edit_user_url(current_user.id) %>" method="GET">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <input type="submit" value="Update">
      </form>

      <form action="<%= session_url %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">

        <input type="submit" value="Logout">
      </form>

    <% else %>

      <form action="<%= new_session_url %>" method="GET">
        <input type="submit" value="Login">
      </form>

      <form action="<%= new_user_url %>" method="GET">
        <input type="submit" value="Sign up">
      </form>
    <% end %>
  </body>
</html>

RedditClone/app/views/users/_user.html.erb
<h1> Hello <%= user.username %> </h1>

RedditClone/app/views/users/edit.html.erb
<form action=" <%= user_url(@user.id) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">

    <label for="user[username]">Username: 
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>

    <input type="submit" value="Update">
</form>

<% if flash[:errors] %>

    <% flash[:errors].each do |error| %>

        <p> <%= error %> </p>

    <% end %>

<% end %>

RedditClone/app/views/users/index.html.erb
<h1> List of Users </h1>

<% @users.each do |user| %>

    <ul> 
        <li><%= user.username %> </li>
    </ul>

<% end %>

RedditClone/app/views/users/new.html.erb
<form action=" <%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="user[username]">Username: 
        <input type="text" name="user[username]" value="">
    </label>
    <label for="user[password]">Password: 
        <input type="password" name="user[password]" value="">
    </label>

    <input type="submit" value="Sign Up">
</form>

<% if flash[:errors] %>

    <% flash[:errors].each do |error| %>

        <p> <%= error %> </p>

    <% end %>

<% end %>

RedditClone/app/views/users/show.html.erb
<%= render 'user', action: :new, user: @user %>